### ISSUE TITLE
Sugestions of improvement in code

### ISSUE THREAD

**Issue by ElsonOtake** [KaskMIL/tm_portfolio#3]
The suggestion for fixing the execution of the npx line command is to check the content of the CSS file.
Suggestion for correction of spelling errors of some words such as "Lenguage" and "Knowldege", for example.

**Comment by KaskMIL** [comment]
Fixed local linters errors and spelling errors.
Thanks!

**Comment by ElsonOtake** [comment]
Congratulations on following the advice. Certainly, the quality of your
presented work will be more appreciated.

Em ter., 26 de abr. de 2022 às 12:08, Tomas Milanesi <
***@***.***> escreveu:
